CREATE TABLE users (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(120)   NOT NULL,
    balance numeric(12, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT ck_users_name_nonblank CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_users_balance_nonnegative CHECK (balance >= 0)
);

CREATE TABLE vehicles (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number varchar(32) NOT NULL,
    user_id      bigint      NOT NULL,
    CONSTRAINT uq_vehicles_plate_number UNIQUE (plate_number),
    CONSTRAINT uq_vehicles_id_user UNIQUE (id, user_id),
    CONSTRAINT fk_vehicles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_vehicles_plate_number_nonblank CHECK (length(btrim(plate_number)) > 0)
);

CREATE INDEX ix_vehicles_user ON vehicles (user_id);

CREATE TABLE cities (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    CONSTRAINT uq_cities_name UNIQUE (name),
    CONSTRAINT ck_cities_name_nonblank CHECK (length(btrim(name)) > 0)
);

CREATE TABLE parking_zones (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(120)   NOT NULL,
    city_id        bigint         NOT NULL,
    price_per_hour numeric(12, 2) NOT NULL,
    active         boolean        NOT NULL DEFAULT true,
    CONSTRAINT uq_parking_zones_city_name UNIQUE (city_id, name),
    CONSTRAINT fk_parking_zones_city FOREIGN KEY (city_id) REFERENCES cities (id),
    CONSTRAINT ck_parking_zones_name_nonblank CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_parking_zones_price_nonnegative CHECK (price_per_hour >= 0)
);

CREATE TABLE parking_sessions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint         NOT NULL,
    vehicle_id  bigint         NOT NULL,
    zone_id     bigint         NOT NULL,
    hourly_rate numeric(12, 2) NOT NULL,
    started_at  timestamptz(3) NOT NULL,
    ended_at    timestamptz(3),
    amount      numeric(12, 2),
    status      varchar(16)    NOT NULL,
    CONSTRAINT fk_parking_sessions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_parking_sessions_vehicle_owner FOREIGN KEY (vehicle_id, user_id) REFERENCES vehicles (id, user_id),
    CONSTRAINT fk_parking_sessions_zone FOREIGN KEY (zone_id) REFERENCES parking_zones (id),
    CONSTRAINT ck_parking_sessions_state CHECK (
        (status = 'ACTIVE' AND ended_at IS NULL AND amount IS NULL)
        OR
        (status = 'COMPLETED' AND ended_at IS NOT NULL AND amount IS NOT NULL)
    ),
    CONSTRAINT ck_parking_sessions_end_after_start CHECK (ended_at IS NULL OR ended_at >= started_at),
    CONSTRAINT ck_parking_sessions_amount_nonnegative CHECK (amount IS NULL OR amount >= 0),
    CONSTRAINT ck_parking_sessions_rate_nonnegative CHECK (hourly_rate >= 0)
);

CREATE UNIQUE INDEX uq_parking_sessions_active_vehicle
    ON parking_sessions (vehicle_id)
    WHERE status = 'ACTIVE';

CREATE INDEX ix_parking_sessions_user_status_start
    ON parking_sessions (user_id, status, started_at DESC, id DESC);

CREATE TABLE payments (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parking_session_id bigint         NOT NULL,
    amount             numeric(12, 2) NOT NULL,
    status             varchar(16)    NOT NULL,
    paid_at            timestamptz(3) NOT NULL,
    CONSTRAINT uq_payments_parking_session UNIQUE (parking_session_id),
    CONSTRAINT fk_payments_parking_session FOREIGN KEY (parking_session_id) REFERENCES parking_sessions (id),
    CONSTRAINT ck_payments_amount_nonnegative CHECK (amount >= 0),
    CONSTRAINT ck_payments_status CHECK (status = 'PAID')
);
